language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run build

notifications:
  webhooks:
    urls:
      - https://reactions.markadkins.design/portfolio/build/passed
    on_success: always
    on_failure: never
    on_start:   never
    on_cancel:  never
    on_error:   never